FROM mcr.microsoft.com/devcontainers/javascript-node:1-20

# Everything below gets ignored by devcontainer.json,
# but can still be used by docker-compose

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the files
COPY . .

EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]
