FROM mcr.microsoft.com/devcontainers/javascript-node:1-20

# Everything below gets ignored by devcontainer.json,
# but can still be used by docker-compose

WORKDIR /app

# Copy the files
COPY . .

EXPOSE 8101

# Command to run the application
CMD ["npm", "run", "dev"]
