FROM mcr.microsoft.com/devcontainers/javascript-node:20

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the files
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
