services:
  frontend:
    image: bcparks-staff-portal-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: bcparks-staff-portal-backend:latest
    environment:
      - PG_CONNECTION_STRING=postgres://user:password@db:5432/mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
