# VSCode devcontainer configuration

services:
  staff-portal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      FONTAWESOME_PACKAGE_TOKEN: ${FONTAWESOME_PACKAGE_TOKEN}
    ports:
      # Expose 8100 for the backend dev server
      - "8100:8100"
      # Expose 8101 for the frontend dev server
      - "8101:8101"
    volumes:
      - .:/app:cached
      # Mount the host's git configuration into the container (global gitignore, etc.)
      - ${HOME}/.config/git:/home/node/.config/git:ro
    command: sleep infinity # Keep the container running
    depends_on:
      - db
    # Just send SIGKILL to stop the container (no grace period for `sleep infinity`)
    # https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop
    stop_signal: SIGKILL

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "8102:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  test-proxy:
    image: caddy:2
    depends_on:
      - staff-portal
    ports:
      - "8103:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro

volumes:
  db-data:
