services:
  frontend:
    image: bcparks-staff-portal-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: bcparks-staff-portal-backend:latest
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
