FROM mcr.microsoft.com/devcontainers/javascript-node:4-24

# Everything below gets ignored by devcontainer.json,
# but can still be used by docker-compose

WORKDIR /app

# No default install or start; user will run npm manually in devcontainer

# Expose 8100 for the backend dev server
EXPOSE 8100

# Expose 8101 for the frontend dev server
EXPOSE 8101
