# Use the official Node.js image as a base
FROM node:20.17

WORKDIR /app

ENV NODE_ENV=production

# Install dependencies
COPY package*.json ./
RUN npm install --production

COPY . .

# Set permissions for OpenShift:
# Grant group ownership to root and enable group write access
RUN mkdir -p /app/.adminjs && \
    chgrp -R 0 /app && \
    chmod -R g=u /app && \
    chmod +x /app/entrypoint.sh

EXPOSE 8100

# Command to run the application
ENTRYPOINT ["./entrypoint.sh"]
