# Use the official Node.js image as a base
FROM node:20.17

WORKDIR /app

ENV NODE_ENV=production

# Install dependencies
COPY package*.json ./
RUN npm install --production

COPY . .

EXPOSE 8100

# Command to run the application
CMD ["npm", "run", "start"]
