FROM mcr.microsoft.com/devcontainers/javascript-node:20

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8000

# Command to run the application
CMD ["npm", "run", "dev"]
