FROM mcr.microsoft.com/devcontainers/javascript-node:1-20

# Everything below gets ignored by devcontainer.json,
# but can still be used by docker-compose

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8100

# Command to run the application
CMD ["npm", "run", "dev"]
