# Use the official Node.js image as a base
FROM node:20.17

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 8000

# Command to run the application
CMD ["npm", "run", "dev"]
