{{ if .Values.pgmonitor.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels: {{ include "crunchy-postgres.labels" . | nindent 4 }}
  name: {{ template "crunchy-postgres.fullname" . }}-crunchy-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "crunchy-postgres.fullname" . }}-crunchy-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-sa
  namespace: {{ .Values.pgmonitor.namespace }}-tools

{{ end }}