{{ if .Values.pgmonitor.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels: {{ include "crunchy-postgres.labels" . | nindent 4 }}
  name: {{ template "crunchy-postgres.fullname" . }}-crunchy-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
{{ end }}