apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-temporary-pvc
  namespace: a7dd13-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
  storageClassName: netapp-file-backup
