instances:
  replicas: 2
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

proxy:
  pgBouncer:
    replicas: 2

pgmonitor:
  namespace: a7dd13 #The high level namespace of your project without the -tools -dev, etc part.
