cluster:
  ssoAuthUrl: https://test.loginproxy.gov.bc.ca/auth
  cmsUrl: https://alpha-test-cms.bcparks.ca

images:
  frontend:
    name: image-registry.openshift-image-registry.svc:5000/a7dd13-tools/frontend-alpha
    tag: test
  backend:
    name: image-registry.openshift-image-registry.svc:5000/a7dd13-tools/backend-alpha
    tag: test

frontend:
  env:
    externalUrl: https://alpha-test-staff.bcparks.ca
    publicUrl: https://alpha-test.bcparks.ca

backend:
  env:
    externalUrl: https://alpha-test-staff-api.bcparks.ca
  postgresSecret: crunchy-postgres-alpha-pguser-postgres
