apiVersion: v1
kind: ServiceAccount
metadata:
  name: githubactions
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}