{{- $random_admin_password := randAlphaNum 32 }}
{{- $random_admin_cookie_password := randAlphaNum 32 }}
{{- $random_admin_session_secret := randAlphaNum 32 }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-adminjs-secret" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    component: {{ .Values.backend.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Release.Name }}-adminjs-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: {{ $random_admin_password | quote }}
  ADMIN_COOKIE_NAME: "adminjs"
  ADMIN_COOKIE_PASSWORD: {{ $random_admin_cookie_password | quote }}
  ADMIN_SESSION_SECRET: {{ $random_admin_session_secret | quote }}
  ADMINJS_RELATIONS_LICENSE_KEY: "value-from-password-vault"
{{- end -}}
