{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-ckeditor-license-key-secret" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-ckeditor-license-key-secret
  labels:
    component: {{ .Values.frontend.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  VITE_CKEDITOR_LICENSE_KEY: "value-from-password-vault"
{{- end -}}
