{{- $random_postgres_app_password := randAlphaNum 32 }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-postgres-secret" .Release.Name)) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    component: crunchy-postgres
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Release.Name }}-postgres-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  POSTGRES_USERNAME: bcparks-{{ .Release.Name }}
  POSTGRES_PASSWORD: {{ $random_postgres_app_password | quote }}
{{- end -}}
