name: Tag image on Git Tag Push

on:
  push:
    tags:
      - "*"

env:
  TOOLS_NAMESPACE: ${{ vars.OPENSHIFT_LICENSE_PLATE }}-tools
  NAMESPACE: ${{ vars.OPENSHIFT_LICENSE_PLATE }}-test

jobs:
  tag:
    runs-on: ubuntu-24.04
    steps:
      - name: Set env
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ vars.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_SERVICE_TOKEN }}

      - name: Tag images
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag frontend-main:${{ env.SHORT_SHA }} frontend-main:${{ env.RELEASE_VERSION }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag backend-main:${{ env.SHORT_SHA }} backend-main:${{ env.RELEASE_VERSION }}

      - name: Delete images tags with commit hash
        run: |
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d frontend-main:${{ env.SHORT_SHA }}
          oc -n ${{ env.TOOLS_NAMESPACE }} tag -d backend-main:${{ env.SHORT_SHA }}
